/**
 * CoCart Session Management Utilities
 *
 * Handles cart operations using the CoCart WordPress plugin API.
 * CoCart provides database-backed cart sessions for headless WooCommerce.
 *
 * CRITICAL: Gabia hosting WAF/mod_security blocks JSON requests to CoCart.
 * All POST/PUT requests MUST use application/x-www-form-urlencoded format.
 *
 * Cart sessions are identified by a cart key (hash) stored in cookies.
 * For guest users, cart key is auto-generated by CoCart on first request.
 * For logged-in users, cart key can be associated with WordPress user ID.
 */

/**
 * Cart item structure from CoCart API
 */
export interface CartItem {
  item_key: string;
  product_id: number;
  variation_id?: number;
  quantity: number;
  name: string;
  price: string;
  line_total: string;
  line_subtotal: string;
  featured_image: string;
}

/**
 * Cart totals from CoCart API
 */
export interface CartTotals {
  subtotal: string;
  subtotal_tax: string;
  total: string;
  total_tax: string;
  currency: string;
  currency_symbol: string;
  currency_decimal_separator: string;
  currency_thousand_separator: string;
}

/**
 * Complete cart structure from CoCart API
 */
export interface Cart {
  cart_key: string;
  items: CartItem[];
  item_count: number;
  totals: CartTotals;
  needs_shipping: boolean;
  needs_payment: boolean;
}

/**
 * Get environment variables with fallback
 */
function getEnvVar(key: string, fallback?: string): string {
  try {
    const { env } = require('./env');
    return env[key];
  } catch {
    return process.env[key] || fallback || '';
  }
}

/**
 * Get CoCart API base URL
 */
function getCoCartApiUrl(): string {
  const wordpressUrl = getEnvVar('WORDPRESS_URL', 'https://82mobile.com');
  const coCartUrl = getEnvVar('COCART_API_URL');

  return coCartUrl || `${wordpressUrl}/wp-json/cocart/v2`;
}

/**
 * Creates headers for CoCart requests
 * @param cartKey - Optional cart key for session persistence
 */
function createCoCartHeaders(cartKey?: string): HeadersInit {
  const headers: HeadersInit = {};

  if (cartKey) {
    headers['Cart-Key'] = cartKey;
  }

  return headers;
}

/**
 * Retrieves the current cart for a session
 *
 * @param cartKey - Optional cart key (auto-generated if not provided)
 * @returns Cart data or null on failure
 *
 * @example
 * const cart = await getCart(cartKey);
 * console.log('Items:', cart?.item_count);
 */
export async function getCart(cartKey?: string): Promise<Cart | null> {
  try {
    const baseUrl = getCoCartApiUrl();

    const response = await fetch(`${baseUrl}/cart`, {
      method: 'GET',
      headers: createCoCartHeaders(cartKey),
    });

    if (!response.ok) {
      console.error('[cart-session] Get cart failed:', response.statusText);
      return null;
    }

    const data = await response.json();
    return data as Cart;
  } catch (error) {
    console.error('[cart-session] Error fetching cart:', error);
    return null;
  }
}

/**
 * Adds an item to the cart
 *
 * CRITICAL: Uses application/x-www-form-urlencoded (not JSON)
 * due to Gabia hosting WAF/mod_security restrictions.
 *
 * @param productId - WooCommerce product ID
 * @param quantity - Quantity to add
 * @param cartKey - Optional cart key
 * @param variationId - Optional variation ID for variable products
 * @returns Updated cart or null on failure
 *
 * @example
 * const cart = await addCartItem(123, 2, cartKey);
 * console.log('New item count:', cart?.item_count);
 */
export async function addCartItem(
  productId: number,
  quantity: number,
  cartKey?: string,
  variationId?: number
): Promise<Cart | null> {
  try {
    const baseUrl = getCoCartApiUrl();

    // CRITICAL: Must use form-encoded format (Gabia WAF blocks JSON)
    const formData = new URLSearchParams({
      id: productId.toString(),
      quantity: quantity.toString(),
    });

    if (variationId) {
      formData.append('variation_id', variationId.toString());
    }

    const response = await fetch(`${baseUrl}/cart/add-item`, {
      method: 'POST',
      headers: {
        ...createCoCartHeaders(cartKey),
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: formData.toString(),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('[cart-session] Add cart item failed:', errorText);
      return null;
    }

    const data = await response.json();
    return data as Cart;
  } catch (error) {
    console.error('[cart-session] Error adding item to cart:', error);
    return null;
  }
}

/**
 * Removes an item from the cart
 *
 * @param itemKey - CoCart item key (unique identifier for cart item)
 * @param cartKey - Optional cart key
 * @returns Updated cart or null on failure
 *
 * @example
 * const cart = await removeCartItem('abc123', cartKey);
 */
export async function removeCartItem(
  itemKey: string,
  cartKey?: string
): Promise<Cart | null> {
  try {
    const baseUrl = getCoCartApiUrl();

    const response = await fetch(`${baseUrl}/cart/item/${itemKey}`, {
      method: 'DELETE',
      headers: createCoCartHeaders(cartKey),
    });

    if (!response.ok) {
      console.error('[cart-session] Remove cart item failed:', response.statusText);
      return null;
    }

    const data = await response.json();
    return data as Cart;
  } catch (error) {
    console.error('[cart-session] Error removing item from cart:', error);
    return null;
  }
}

/**
 * Updates the quantity of an item in the cart
 *
 * CRITICAL: Uses application/x-www-form-urlencoded (not JSON)
 * due to Gabia hosting WAF/mod_security restrictions.
 *
 * @param itemKey - CoCart item key
 * @param quantity - New quantity (0 to remove)
 * @param cartKey - Optional cart key
 * @returns Updated cart or null on failure
 *
 * @example
 * const cart = await updateCartItem('abc123', 3, cartKey);
 */
export async function updateCartItem(
  itemKey: string,
  quantity: number,
  cartKey?: string
): Promise<Cart | null> {
  try {
    const baseUrl = getCoCartApiUrl();

    // CRITICAL: Must use form-encoded format (Gabia WAF blocks JSON)
    const formData = new URLSearchParams({
      quantity: quantity.toString(),
    });

    const response = await fetch(`${baseUrl}/cart/item/${itemKey}`, {
      method: 'POST',
      headers: {
        ...createCoCartHeaders(cartKey),
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: formData.toString(),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('[cart-session] Update cart item failed:', errorText);
      return null;
    }

    const data = await response.json();
    return data as Cart;
  } catch (error) {
    console.error('[cart-session] Error updating cart item:', error);
    return null;
  }
}

/**
 * Clears all items from the cart
 *
 * @param cartKey - Optional cart key
 * @returns Empty cart or null on failure
 *
 * @example
 * const cart = await clearCart(cartKey);
 * console.log('Cart cleared:', cart?.item_count === 0);
 */
export async function clearCart(cartKey?: string): Promise<Cart | null> {
  try {
    const baseUrl = getCoCartApiUrl();

    const response = await fetch(`${baseUrl}/cart/clear`, {
      method: 'POST',
      headers: createCoCartHeaders(cartKey),
    });

    if (!response.ok) {
      console.error('[cart-session] Clear cart failed:', response.statusText);
      return null;
    }

    const data = await response.json();
    return data as Cart;
  } catch (error) {
    console.error('[cart-session] Error clearing cart:', error);
    return null;
  }
}

/**
 * Gets cart totals without full cart details
 *
 * Useful for displaying cart total in navigation without loading all items.
 *
 * @param cartKey - Optional cart key
 * @returns Cart totals or null on failure
 */
export async function getCartTotals(cartKey?: string): Promise<CartTotals | null> {
  try {
    const baseUrl = getCoCartApiUrl();

    const response = await fetch(`${baseUrl}/cart/totals`, {
      method: 'GET',
      headers: createCoCartHeaders(cartKey),
    });

    if (!response.ok) {
      console.error('[cart-session] Get cart totals failed:', response.statusText);
      return null;
    }

    const data = await response.json();
    return data as CartTotals;
  } catch (error) {
    console.error('[cart-session] Error fetching cart totals:', error);
    return null;
  }
}

/**
 * Gets the number of items in the cart
 *
 * Convenience function for displaying item count in UI.
 *
 * @param cartKey - Optional cart key
 * @returns Item count or 0 on failure
 */
export async function getCartItemCount(cartKey?: string): Promise<number> {
  const cart = await getCart(cartKey);
  return cart?.item_count || 0;
}
