import { jwtVerify } from 'jose';

/**
 * WordPress JWT Authentication Utilities
 *
 * Handles JWT token generation and verification for WordPress REST API authentication.
 * Uses the WordPress JWT Authentication plugin endpoint.
 *
 * Security notes:
 * - JWT tokens should be stored in httpOnly cookies (not localStorage)
 * - Uses jose library for Edge Runtime compatibility (not jsonwebtoken)
 * - Tokens are generated by WordPress, Next.js only verifies them
 */

/**
 * JWT token response from WordPress
 */
export interface JwtTokenResponse {
  token: string;
  user: {
    id: number;
    email: string;
    displayName: string;
  };
}

/**
 * JWT verification result
 */
export interface JwtVerificationResult {
  valid: boolean;
  payload?: any;
  error?: string;
}

/**
 * Get environment variables with fallback
 * Handles case where env validation hasn't run yet
 */
function getEnvVar(key: string, fallback?: string): string {
  try {
    const { env } = require('./env');
    return env[key];
  } catch {
    const value = process.env[key] || fallback;
    if (!value) {
      console.warn(`[wordpress-auth] Environment variable ${key} not found`);
    }
    return value || '';
  }
}

/**
 * Generates a JWT token by authenticating with WordPress
 *
 * Calls the WordPress JWT Authentication plugin endpoint:
 * POST /wp-json/jwt-auth/v1/token
 *
 * @param username - WordPress username
 * @param password - WordPress password
 * @returns JWT token and user info, or null on failure
 *
 * @example
 * const result = await getJwtToken('admin', 'password123');
 * if (result) {
 *   console.log('Token:', result.token);
 *   console.log('User:', result.user.email);
 * }
 */
export async function getJwtToken(
  username: string,
  password: string
): Promise<JwtTokenResponse | null> {
  try {
    const wordpressUrl = getEnvVar('WORDPRESS_URL', 'https://82mobile.com');

    const response = await fetch(
      `${wordpressUrl}/wp-json/jwt-auth/v1/token`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ username, password }),
      }
    );

    if (!response.ok) {
      const error = await response.json();
      console.error('[wordpress-auth] JWT token generation failed:', error);
      return null;
    }

    const data = await response.json();

    return {
      token: data.token,
      user: {
        id: data.user_id || 0,
        email: data.user_email || '',
        displayName: data.user_display_name || data.user_nicename || username,
      },
    };
  } catch (error) {
    console.error('[wordpress-auth] Error generating JWT token:', error);
    return null;
  }
}

/**
 * Verifies a JWT token using the JWT secret
 *
 * Uses jose library for Edge Runtime compatibility.
 * The token was generated by WordPress using the same JWT_SECRET.
 *
 * @param token - JWT token string to verify
 * @returns Verification result with validity and payload
 *
 * @example
 * const result = await verifyJwtToken(token);
 * if (result.valid) {
 *   console.log('User ID:', result.payload.sub);
 * }
 */
export async function verifyJwtToken(
  token: string
): Promise<JwtVerificationResult> {
  try {
    const jwtSecret = getEnvVar('JWT_SECRET');

    if (!jwtSecret) {
      return {
        valid: false,
        error: 'JWT_SECRET not configured',
      };
    }

    // jose requires secret as Uint8Array
    const secret = new TextEncoder().encode(jwtSecret);

    // Verify JWT token
    const { payload } = await jwtVerify(token, secret);

    return {
      valid: true,
      payload,
    };
  } catch (error: any) {
    console.error('[wordpress-auth] JWT verification failed:', error.message);
    return {
      valid: false,
      error: error.message || 'Token verification failed',
    };
  }
}

/**
 * Creates authorization headers for authenticated WordPress API requests
 *
 * @param token - JWT token
 * @returns Headers object with Authorization header
 *
 * @example
 * const headers = createAuthHeaders(token);
 * fetch('https://82mobile.com/wp-json/wp/v2/posts', { headers });
 */
export function createAuthHeaders(token: string): HeadersInit {
  return {
    'Authorization': `Bearer ${token}`,
  };
}

/**
 * Validates a token and returns the user payload if valid
 *
 * Convenience function that combines verification and payload extraction.
 *
 * @param token - JWT token
 * @returns User payload or null if invalid
 *
 * @example
 * const user = await getUserFromToken(token);
 * if (user) {
 *   console.log('User email:', user.email);
 * }
 */
export async function getUserFromToken(token: string): Promise<any | null> {
  const result = await verifyJwtToken(token);
  return result.valid ? result.payload : null;
}

/**
 * Refreshes a JWT token
 *
 * Note: WordPress JWT Authentication plugin doesn't have built-in refresh tokens.
 * This would require re-authentication with username/password.
 *
 * @param username - WordPress username
 * @param password - WordPress password
 * @returns New JWT token or null
 */
export async function refreshJwtToken(
  username: string,
  password: string
): Promise<JwtTokenResponse | null> {
  // WordPress JWT plugin doesn't have refresh tokens
  // Must re-authenticate to get a new token
  return getJwtToken(username, password);
}
